/**
 * Write the corpus `manifest.json` (everything, for a comparison tool) and
 * `index.md` (a table a tester can scan) beside the generated files.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { MANIFEST_FILE } from "./runner.mjs";

const INDEX_FILE = "index.md";
const PERCENT = 100;
const UNIT_DECIMALS = 4;
const PERCENT_DECIMALS = 1;

function units(value) {
  return typeof value === "number" ? value.toFixed(UNIT_DECIMALS) : String(value);
}

function percent(value) {
  return typeof value === "number"
    ? `${(value * PERCENT).toFixed(PERCENT_DECIMALS)}%`
    : String(value);
}

function netChangeCell(headline, kind) {
  return `${units(headline.netUnitChange[kind])} (${percent(headline.netPercentChange[kind])})`;
}

function breachesCell(trading) {
  const breaches = Object.entries(trading).flatMap(([kind, bands]) =>
    bands
      .filter((b) => !String(b.satisfied).startsWith("Yes"))
      .map((b) => `${kind} ${b.distinctiveness}`),
  );
  return breaches.length > 0 ? breaches.join(", ") : "—";
}

function checksCell(checks) {
  if (!checks || checks.length === 0) {
    return "—";
  }
  const failed = checks.filter((c) => !c.passed).length;
  return failed === 0 ? `✓ ${checks.length}` : `✗ ${failed} of ${checks.length}`;
}

function tableRow(cells) {
  return `| ${cells.join(" | ")} |`;
}

function renderRow(entry) {
  const title = `**${entry.title}**<br>\`${entry.files.workbook}\``;
  const rejected = entry.rejectedInputs.length || "—";
  if (!entry.metric) {
    return tableRow([title, "not recalculated", "", "", "", "", rejected, "—"]);
  }
  const { headline, trading, rowWarnings } = entry.metric;
  return tableRow([
    title,
    netChangeCell(headline, "area"),
    netChangeCell(headline, "hedgerow"),
    netChangeCell(headline, "watercourse"),
    breachesCell(trading),
    rowWarnings.length || "—",
    rejected,
    checksCell(entry.checks),
  ]);
}

function renderIndex({ entries, seed, templatePath }) {
  const lines = [
    "# Synthetic metric workbooks",
    "",
    "One scenario, both artefacts: each row is a baseline / post-intervention",
    "GeoPackage pair and the Statutory Biodiversity Metric workbook written from",
    "it. The figures are the metric's own, recalculated from its unmodified",
    "formulas — including its known cumulative-surplus error (BMD-993), which is",
    "deliberately not corrected. Generated by `npm run generate:workbooks`.",
    "",
    `Seed **${seed}** · template \`${path.basename(templatePath)}\` · ${entries.length} scenario(s).`,
    "",
    "Net change is units (percentage). *Warnings* counts distinct warnings the",
    "metric shows on feature rows; *Rejected inputs* counts values the workbook's",
    "own drop-down lists do not offer (such a row computes nothing).",
    "",
    "| Scenario | Area net change | Hedgerow net change | Watercourse net change | Trading rules not met | Warnings | Rejected inputs | Checks |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...entries.map(renderRow),
    "",
  ];
  return lines.join("\n");
}

/**
 * @param {string} outDir
 * @param {object} run { entries, seed, templatePath }
 */
export function writeWorkbookManifest(outDir, run) {
  const manifestPath = path.join(outDir, MANIFEST_FILE);
  const indexPath = path.join(outDir, INDEX_FILE);
  const manifest = {
    seed: run.seed,
    template: path.basename(run.templatePath),
    recalculated: run.entries.every((e) => e.metric),
    scenarios: run.entries,
  };
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(indexPath, renderIndex(run));
  return { manifestPath, indexPath };
}
