/**
 * Write the corpus `manifest.json` (everything, for a comparison tool) and
 * `index.md` (a table per purpose a tester can scan) at the root of the
 * output folder.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

export const MANIFEST_FILE = "manifest.json";
const INDEX_FILE = "index.md";
const PERCENT = 100;
const UNIT_DECIMALS = 4;
const PERCENT_DECIMALS = 1;
const NONE = "—";

function units(value) {
  return typeof value === "number"
    ? value.toFixed(UNIT_DECIMALS)
    : String(value);
}

function percent(value) {
  return typeof value === "number"
    ? `${(value * PERCENT).toFixed(PERCENT_DECIMALS)}%`
    : String(value);
}

function engineGainCell(gain) {
  if (!gain) {
    return NONE;
  }
  // Number.isFinite guards null as well as NaN/Infinity — an all-skipped
  // scenario can make the engine divide 0 by 0.
  const shown = Number.isFinite(gain.percentage)
    ? `${gain.percentage.toFixed(PERCENT_DECIMALS)}%`
    : "n/a";
  return `${gain.expected} (${shown})`;
}

function netChangeCell(headline, kind) {
  return `${units(headline.netUnitChange[kind])} (${percent(headline.netPercentChange[kind])})`;
}

function breachesCell(trading) {
  const breaches = Object.entries(trading).flatMap(([kind, bands]) =>
    bands
      .filter((b) => !String(b.satisfied).startsWith("Yes"))
      .map((b) => `${kind} ${b.distinctiveness}`),
  );
  return breaches.length > 0 ? breaches.join(", ") : NONE;
}

function checksCell(checks) {
  if (!checks || checks.length === 0) {
    return NONE;
  }
  const failed = checks.filter((c) => !c.passed).length;
  return failed === 0
    ? `✓ ${checks.length}`
    : `✗ ${failed} of ${checks.length}`;
}

function filesCell(files) {
  return Object.values(files)
    .map((f) => `\`${path.basename(f)}\``)
    .join("<br>");
}

function tableRow(cells) {
  return `| ${cells.join(" | ")} |`;
}

function columns(recalculated) {
  const metric = recalculated
    ? [
        "Area net change",
        "Hedgerow net change",
        "Watercourse net change",
        "Trading rules not met",
        "Warnings",
        "Rejected inputs",
      ]
    : [];
  return [
    "Scenario",
    "Subject",
    "Files",
    "Net gain (our engine)",
    ...metric,
    "Checks",
  ];
}

function renderRow(entry, recalculated) {
  const cells = [
    `**${entry.title}**<br>${entry.description}`,
    `${entry.subject.ref} — ${entry.subject.note}`,
    filesCell(entry.files),
    engineGainCell(entry.gain),
  ];
  if (recalculated) {
    const { headline, trading, rowWarnings } = entry.metric;
    cells.push(
      netChangeCell(headline, "area"),
      netChangeCell(headline, "hedgerow"),
      netChangeCell(headline, "watercourse"),
      breachesCell(trading),
      rowWarnings.length || NONE,
      entry.rejectedInputs.length || NONE,
    );
  }
  cells.push(checksCell(entry.checks));
  return tableRow(cells);
}

function renderPurpose(purpose, entries, recalculated) {
  const heads = columns(recalculated);
  return [
    `## ${purpose}`,
    "",
    tableRow(heads),
    tableRow(heads.map(() => "---")),
    ...entries.map((entry) => renderRow(entry, recalculated)),
    "",
  ].join("\n");
}

function describeRun({ entries, seed, templatePath, recalculated }) {
  const purposes = new Set(entries.map((e) => e.purpose)).size;
  const lines = [
    `Seed **${seed}** · ${entries.length} scenario(s) across ${purposes} purpose(s).`,
  ];
  if (!templatePath) {
    lines.push(
      "",
      "GeoPackages only (`--no-workbooks`). Net gain is priced through our own engine.",
    );
  } else if (recalculated) {
    lines.push(
      "",
      `Each scenario also has a metric workbook, written into \`${path.basename(templatePath)}\` and recalculated. Its figures are the metric's own, from its unmodified formulas — including its known cumulative-surplus error, which is deliberately not corrected. *Warnings* counts distinct warnings the metric shows on feature rows; *Rejected inputs* counts values the workbook's own drop-down lists do not offer.`,
    );
  } else {
    lines.push(
      "",
      `Each scenario also has a metric workbook, written into \`${path.basename(templatePath)}\` but not recalculated (\`--no-recalc\`). Excel recalculates it on open.`,
    );
  }
  return lines;
}

function renderIndex(run) {
  const recalculated = run.entries.every((e) => e.metric);
  const purposes = [...new Set(run.entries.map((e) => e.purpose))];
  const lines = [
    "# BNG scenarios",
    "",
    "Paired baseline / post-intervention GeoPackages from the bng-library",
    "scenario catalogue, generated by `npm run generate:scenarios`. Each row",
    "names the feature a tester should open to exercise the scenario.",
    "",
    ...describeRun({ ...run, recalculated }),
    "",
    ...purposes.map((purpose) =>
      renderPurpose(
        purpose,
        run.entries.filter((e) => e.purpose === purpose),
        recalculated,
      ),
    ),
  ];
  return lines.join("\n");
}

/**
 * @param {string} outDir
 * @param {object} run { entries, seed, templatePath? }
 */
export function writeScenarioManifest(outDir, run) {
  const manifestPath = path.join(outDir, MANIFEST_FILE);
  const indexPath = path.join(outDir, INDEX_FILE);
  const manifest = {
    seed: run.seed,
    template: run.templatePath ? path.basename(run.templatePath) : null,
    recalculated: run.entries.every((e) => e.metric),
    scenarios: run.entries,
  };
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(indexPath, renderIndex(run));
  return { manifestPath, indexPath };
}
