/**
 * Write the corpus `manifest.json` (everything, for a comparison tool) and
 * `index.md` (a table per purpose a tester can scan) at the root of the
 * output folder. A filtered run merges its scenarios into the corpus already
 * there rather than replacing it.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { METRIC_CORRECTIONS } from "#workbook-writer";

export const MANIFEST_FILE = "manifest.json";
const INDEX_FILE = "index.md";
const PERCENT = 100;
const UNIT_DECIMALS = 4;
const PERCENT_DECIMALS = 1;
const NONE = "—";

function units(value) {
  return typeof value === "number"
    ? value.toFixed(UNIT_DECIMALS)
    : String(value);
}

function percent(value) {
  return typeof value === "number"
    ? `${(value * PERCENT).toFixed(PERCENT_DECIMALS)}%`
    : String(value);
}

function engineGainCell(gain) {
  if (!gain) {
    return NONE;
  }
  // Number.isFinite guards null as well as NaN/Infinity — an all-skipped
  // scenario can make the engine divide 0 by 0.
  const shown = Number.isFinite(gain.percentage)
    ? `${gain.percentage.toFixed(PERCENT_DECIMALS)}%`
    : "n/a";
  return `${gain.expected} (${shown})`;
}

function netChangeCell(headline, kind) {
  return `${units(headline.netUnitChange[kind])} (${percent(headline.netPercentChange[kind])})`;
}

function breachesCell(trading) {
  const breaches = Object.entries(trading).flatMap(([kind, bands]) =>
    bands
      .filter((b) => !String(b.satisfied).startsWith("Yes"))
      .map((b) => `${kind} ${b.distinctiveness}`),
  );
  return breaches.length > 0 ? breaches.join(", ") : NONE;
}

function checksCell(checks) {
  if (!checks || checks.length === 0) {
    return NONE;
  }
  const failed = checks.filter((c) => !c.passed).length;
  return failed === 0
    ? `✓ ${checks.length}`
    : `✗ ${failed} of ${checks.length}`;
}

function filesCell(files) {
  return Object.values(files)
    .map((f) => `\`${path.basename(f)}\``)
    .join("<br>");
}

function tableRow(cells) {
  return `| ${cells.join(" | ")} |`;
}

function columns(recalculated) {
  const metric = recalculated
    ? [
        "Area net change",
        "Hedgerow net change",
        "Watercourse net change",
        "Trading rules not met",
        "Warnings",
        "Rejected inputs",
      ]
    : [];
  return [
    "Scenario",
    "Subject",
    "Files",
    "Net gain (our engine)",
    ...metric,
    "Checks",
  ];
}

function renderRow(entry, recalculated) {
  const cells = [
    `**${entry.title}**<br>${entry.description}`,
    `${entry.subject.ref} — ${entry.subject.note}`,
    filesCell(entry.files),
    engineGainCell(entry.gain),
  ];
  if (recalculated) {
    const { headline, trading, rowWarnings } = entry.metric;
    cells.push(
      netChangeCell(headline, "area"),
      netChangeCell(headline, "hedgerow"),
      netChangeCell(headline, "watercourse"),
      breachesCell(trading),
      rowWarnings.length || NONE,
      entry.rejectedInputs.length || NONE,
    );
  }
  cells.push(checksCell(entry.checks));
  return tableRow(cells);
}

function renderPurpose(purpose, entries, recalculated) {
  const heads = columns(recalculated);
  return [
    `## ${purpose}`,
    "",
    tableRow(heads),
    tableRow(heads.map(() => "---")),
    ...entries.map((entry) => renderRow(entry, recalculated)),
    "",
  ].join("\n");
}

function describeRun({ entries, seed, templatePath, recalculated }) {
  const purposes = new Set(entries.map((e) => e.purpose)).size;
  const lines = [
    `Seed **${seed}** · ${entries.length} scenario(s) across ${purposes} purpose(s).`,
  ];
  if (!templatePath) {
    lines.push(
      "",
      "GeoPackages only (`--no-workbooks`). Net gain is priced through our own engine.",
    );
  } else if (recalculated) {
    lines.push(
      "",
      `Each scenario also has a metric workbook, written into \`${path.basename(templatePath)}\` and recalculated. Its figures are the metric's own, from Defra's formulas, except that the metric's known bugs are corrected: \`corrections\` in \`manifest.json\` lists each one. *Warnings* counts distinct warnings the metric shows on feature rows; *Rejected inputs* counts values the workbook's own drop-down lists do not offer.`,
    );
  } else {
    lines.push(
      "",
      `Each scenario also has a metric workbook, written into \`${path.basename(templatePath)}\` but not recalculated (\`--no-recalc\`). Excel recalculates it on open.`,
    );
  }
  return lines;
}

function renderIndex(run) {
  const recalculated = run.entries.every((e) => e.metric);
  const purposes = [...new Set(run.entries.map((e) => e.purpose))];
  const lines = [
    "# BNG scenarios",
    "",
    "Paired baseline / post-intervention GeoPackages from the bng-library",
    "scenario catalogue, generated by `npm run generate:scenarios`. Each row",
    "names the feature a tester should open to exercise the scenario.",
    "",
    ...describeRun({ ...run, recalculated }),
    "",
    ...purposes.map((purpose) =>
      renderPurpose(
        purpose,
        run.entries.filter((e) => e.purpose === purpose),
        recalculated,
      ),
    ),
  ];
  return lines.join("\n");
}

function templateName(templatePath) {
  return templatePath ? path.basename(templatePath) : null;
}

function correctionIds(corrections) {
  return (corrections ?? []).map((c) => c.id).join(", ") || "none";
}

/**
 * The manifest of the corpus already in the output folder, or null when
 * there is none. Throws if it is there but unreadable.
 */
export function readScenarioManifest(outDir) {
  const manifestPath = path.join(outDir, MANIFEST_FILE);
  if (!existsSync(manifestPath)) {
    return null;
  }
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  if (!Array.isArray(manifest?.scenarios)) {
    throw new TypeError(`${manifestPath} has no scenarios list`);
  }
  return manifest;
}

/**
 * Every way a filtered run differs from the corpus it would be merged into.
 * Any difference would leave the manifest describing a corpus no single run
 * produced, so the caller refuses the merge.
 *
 * @param {object} previous the existing manifest
 * @param {object} run { seed, templatePath?, recalculate }
 * @returns {string[]} empty when the run fits the corpus
 */
export function corpusConflicts(previous, { seed, templatePath, recalculate }) {
  const template = templateName(templatePath);
  const checks = [
    seedConflict(previous, seed),
    templateConflict(previous, template),
  ];
  // Recalculation and corrections only mean something with workbooks.
  if (template) {
    checks.push(
      recalcConflict(previous, recalculate),
      correctionsConflict(previous),
    );
  }
  return checks.filter(Boolean);
}

function seedConflict(previous, seed) {
  return previous.seed === seed
    ? null
    : `seed ${seed}, but the corpus has seed ${previous.seed}`;
}

function templateConflict(previous, template) {
  const describe = (name) => name ?? "none (--no-workbooks)";
  return previous.template === template
    ? null
    : `template ${describe(template)}, but the corpus has ${describe(previous.template)}`;
}

function recalcConflict(previous, recalculate) {
  if (previous.recalculated === recalculate) {
    return null;
  }
  return recalculate
    ? "recalculated workbooks, but the corpus was written with --no-recalc"
    : "--no-recalc, but the corpus's workbooks are recalculated";
}

function correctionsConflict(previous) {
  const corrections = correctionIds(METRIC_CORRECTIONS);
  const previousCorrections = correctionIds(previous.corrections);
  return corrections === previousCorrections
    ? null
    : `metric corrections ${corrections}, but the corpus has ${previousCorrections}`;
}

/**
 * The corpus's entries with a filtered run's in place of the ones they
 * regenerate, in catalogue order. Entries for scenarios no longer in the
 * catalogue are returned as `dropped`, for the caller to remove their files.
 *
 * @param {object[]} previousEntries the existing manifest's scenarios
 * @param {object[]} entries the entries this run built
 * @param {string[]} catalogueIds every scenario id, in catalogue order
 */
export function mergeScenarioEntries(previousEntries, entries, catalogueIds) {
  const byId = new Map(previousEntries.map((e) => [e.id, e]));
  for (const entry of entries) {
    byId.set(entry.id, entry);
  }
  const inCatalogue = new Set(catalogueIds);
  return {
    entries: catalogueIds
      .filter((id) => byId.has(id))
      .map((id) => byId.get(id)),
    dropped: [...byId.values()].filter((e) => !inCatalogue.has(e.id)),
  };
}

/**
 * @param {string} outDir
 * @param {object} run { entries, seed, templatePath? }
 */
export function writeScenarioManifest(outDir, run) {
  const manifestPath = path.join(outDir, MANIFEST_FILE);
  const indexPath = path.join(outDir, INDEX_FILE);
  const manifest = {
    seed: run.seed,
    template: templateName(run.templatePath),
    corrections: run.templatePath ? METRIC_CORRECTIONS : [],
    recalculated: run.entries.every((e) => e.metric),
    scenarios: run.entries,
  };
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(indexPath, renderIndex(run));
  return { manifestPath, indexPath };
}
